#!/Python27/python.exe
print "Content-type:text/html\r\n\r\n"
print "<html lang='en'>"
print "<head>"
print "<meta charset='utf-8'>"
print "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
print "<link rel='shortcut icon' href='img/favicon.png'>"
print "<title></title>"
import JcLink
print "</head>"
print "<body>"
print "<!-- container section start -->"
print "<section id='container' class=''>"
import Header
# <!--sidebar start-->
print "<aside>"
print "<div id='sidebar'  class='nav-collapse '>"
# <!-- sidebar menu start-->
print "<ul class='sidebar-menu'>"
print "<li class='active'>"
print "<a class='' href='mainpage.py'>"
print "<i class='icon_house_alt'></i>"
print "<span>Dashboard</span>"
print "</a>"
print "</li>"
print "<li class='sub-menu'>"
print "<a href='javascript:;' class=''>"
print "<i class='icon_document_alt'></i>"
print "<span>Employees</span>"
print "<span class='menu-arrow arrow_carrot-right'></span>"
print "</a>"
print "<ul class='sub'>"
print "<li><a class='' href='add_employee.py'>Add Employees</a></li>                          "
print "<li><a class='' href='view_employee.py'>View  Employees</a></li>"
print "<li><a class='' href='view_projectmanager.py'>View Project Manager</a></li>"
print "</ul></li>"
print "<li class='sub-menu'>"
print "<a href='javascript:;' class=''>"
print "<i class='icon_document_alt'></i>"
print "<span>Project Register</span>"
print "<span class='menu-arrow arrow_carrot-right'></span>"
print "</a>"
print "<ul class='sub'>"
print "<li><a class='' href='add_project.py'>Add Project</a></li>"
print "<li><a class='' href='view_project.py'>View Project</a></li>"
print "</ul></li>"

print "<li class='sub-menu'>"
print "<a href='javascript:;' class=''>"
print "<i class='icon_document_alt'></i>"
print "<span>Project Report</span>"
print "<span class='menu-arrow arrow_carrot-right'></span>"
print "</a>"
print "<ul class='sub'>"
print "<li><a class='' href='project_employee_report.py'>Employee Report</a></li>" # pending completed report
print "<li><a class='' href='project_leader_report.py'>Team Leader</a></li>" # empid,empname,keyskill,teamsize,duration
print "</ul></li>"

print "</ul>"
# <!-- sidebar menu end-->
print "</div>"
print "</aside>"
print "<!--sidebar end-->"

# <!--main content start-->
print "<section id='main-content'>"
print "<section class='wrapper'>"
print "<div class='row'>"
print "<div class='col-lg-12'>"
print "<h3 class='page-header'><i class='fa fa-files-o'></i> New Project</h3>"
print "<ol class='breadcrumb'>"
print "<li><i class='fa fa-home'></i><a href='mainpage.py'>Home</a></li>"
print "<li><i class='icon_document_alt'></i>Projects</li>"
print "<li><i class='fa fa-files-o'></i>Add Projects</li>"
print "</ol></div></div>"
# <!-- Form validations -->              
print "<div class='row'>"
print "<div class='col-lg-12'>"
print "<section class='panel'>"
print "<header class='panel-heading'>"
print "Add Projects"
print "</header>"
print "<div class='panel-body'>"
print "<div class='form'>"
print "<form class='form-validate form-horizontal' id='feedback_form' method='get' action='insert_project.py'>"
print "<div class='form-group '>"
print "<label for='cname' class='control-label col-lg-2'>Project Name:<span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input class='form-control' id='projectname' name='projectname' maxlength='25' type='text' required />"
print "</div></div>"
print "<div class='form-group '>"
print "<label for='cemail' class='control-label col-lg-2'>Coding Language:<span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input class='form-control ' id='codinglanguage' type='text' name='codinglanguage' required />"
print "</div></div>"

print "<div class='form-group '>"
print "<label for='cemail' class='control-label col-lg-2'>Database:<span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input class='form-control ' id='databasename' type='text' name='databasename' required />"
print "</div></div>"

print "<div class='form-group '>"
print "<label for='cemail' class='control-label col-lg-2'>Duration:<span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input class='form-control ' id='duration' type='text' name='duration' required />"
print "</div></div>"
print "<div class='form-group '>"
print "<label for='curl' class='control-label col-lg-2'>Register Date:</label>"
print "<div class='col-lg-10'>"
print "<input class='form-control ' id='registerdate' type='date' name='registerdate' />"
print "</div></div>"
print "<div class='form-group '>"
print "<label for='curl' class='control-label col-lg-2'>Project Description:</label>"
print "<div class='col-lg-10'>"
print "<textarea class='form-control' name='desc' maxlength='60000'/></textarea>"
print "</div></div>"
print "<div class='form-group'>"
print "<div class='col-lg-offset-2 col-lg-10'>"
print "<button class='btn btn-primary' type='submit'>Save</button>"
print "<button class='btn btn-default' type='button'>Cancel</button>"
print "</div></div></form></div></div></section></div></div></section></section>"
# <!--main content end-->
print "<div class='text-right'>"
print "<div class='credits'>"
print "</div></div></section>"
# <!-- container section end -->

print "</body>"
print "</html>" 
