#!/Python27/python.exe
print "Content-type:text/html\r\n\r\n"
print "<html lang='en'>"
print "<head>"
print "<meta charset='utf-8'>"
print "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
print "<link rel='shortcut icon' href='img/favicon.png'>"
print "<title></title>"
import JcLink
print "</head>"
print "<body>"
print "<!-- container section start -->"
print "<section id='container' class=''>"
import Header
# <!--sidebar start-->
print "<aside>"
print "<div id='sidebar'  class='nav-collapse '>"
# <!-- sidebar menu start-->
print "<ul class='sidebar-menu'>"
print "<li class='active'>"
print "<a class='' href='mainpage.py'>"
print "<i class='icon_house_alt'></i>"
print "<span>Dashboard</span>"
print "</a>"
print "</li>"
print "<li class='sub-menu'>"
print "<a href='javascript:;' class=''>"
print "<i class='icon_document_alt'></i>"
print "<span>Employees</span>"
print "<span class='menu-arrow arrow_carrot-right'></span>"
print "</a>"
print "<ul class='sub'>"
print "<li><a class='' href='add_employee.py'>Add Employees</a></li>                          "
print "<li><a class='' href='view_employee.py'>View  Employees</a></li>"
print "<li><a class='' href='view_projectmanager.py'>View Project Manager</a></li>"
print "</ul></li>"
print "<li class='sub-menu'>"
print "<a href='javascript:;' class=''>"
print "<i class='icon_document_alt'></i>"
print "<span>Project Register</span>"
print "<span class='menu-arrow arrow_carrot-right'></span>"
print "</a>"
print "<ul class='sub'>"
print "<li><a class='' href='add_project.py'>Add Project</a></li>"
print "<li><a class='' href='view_project.py'>View Project</a></li>"
print "</ul></li>"
print "<li class='sub-menu'>"
print "<a href='javascript:;' class=''>"
print "<i class='icon_document_alt'></i>"
print "<span>Project Report</span>"
print "<span class='menu-arrow arrow_carrot-right'></span>"
print "</a>"
print "<ul class='sub'>"
print "<li><a class='' href='project_employee_report.py'>Employee Report</a></li>" # pending completed report
print "<li><a class='' href='project_leader_report.py'>Team Leader</a></li>" # empid,empname,keyskill,teamsize,duration
print "</ul></li>"
print "</ul></li></ul>"
# <!-- sidebar menu end-->
print "</div>"
print "</aside>"
print "<!--sidebar end-->"

# <!--main content start-->
print "<section id='main-content'>"
print "<section class='wrapper'>"
print "<div class='row'>"
print "<div class='col-lg-12'>"
print "<h3 class='page-header'><i class='fa fa-files-o'></i> New Employee</h3>"
print "<ol class='breadcrumb'>"
print "<li><i class='fa fa-home'></i><a href='mainpage.py'>Home</a></li>"
print "<li><i class='icon_document_alt'></i>Employees</li>"
print "<li><i class='fa fa-files-o'></i>Add Employees</li>"
print "</ol></div></div>"
# <!-- Form validations -->              
print "<div class='row'>"
print "<div class='col-lg-12'>"
print "<section class='panel'>"
print "<header class='panel-heading'>"
print "Add Employees"
print "</header>"
print "<div class='panel-body'>"
print "<div class='form'>"
print "<form class='form-validate form-horizontal' id='feedback_form' method='get' action='insert_employee.py'>"
print "<div class='form-group '>"
print "<label for='cname' class='control-label col-lg-2'>UserName:<span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input class='form-control' id='username' name='username' maxlength='25' type='text' required />"
print "</div></div>"
print "<div class='form-group '>"
print "<label for='cemail' class='control-label col-lg-2'>Password:<span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input class='form-control ' id='password' type='password' name='password' required />"
print "</div></div>"

print "<div class='form-group '>"
print "<label for='cemail' class='control-label col-lg-2'>MailID:<span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input class='form-control ' id='email' type='email' name='email' required />"
print "</div></div>"

print "<div class='form-group '>"
print "<label for='cemail' class='control-label col-lg-2'>Date of Birth:<span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input class='form-control ' id='dob' type='date' name='dob' required />"
print "</div></div>"

print "<div class='form-group '>"
print "<label for='cemail' class='control-label col-lg-2'>Gender:<span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input id='gender' type='radio' name='gender' value='Male'>Male<br>"
print "<input id='gender' type='radio' name='gender' value='Female'>Female"
print "</div></div>"
print "<div class='form-group '>"
print "<label for='curl' class='control-label col-lg-2'>Address:</label>"
print "<div class='col-lg-10'>"
print "<input class='form-control ' id='address' type='text' name='address' />"

print "</div></div>"
print "<div class='form-group '>"
print "<label for='cname' class='control-label col-lg-2'>City: <span class='required'>*</span></label>"
print "<div class='col-lg-10'>"
print "<input class='form-control' id='city' name='city' maxlength='50' type='text' required />"
print "</div></div>"
print "<div class='form-group '>"
print "<label for='ccomment' class='control-label col-lg-2'>Pincode:</label>"
print "<div class='col-lg-10'>"
print "<input  class='form-control' type=text id='pcode' name='pcode' required/>"
print "</div></div>"

print "<div class='form-group '>"
print "<label for='ccomment' class='control-label col-lg-2'>Mobile Number:</label>"
print "<div class='col-lg-10'>"
print "<input  class='form-control' type=text id='mobile' name='mobile' required/>"
print "</div></div>"


print "<div class='form-group '>"
print "<label for='ccomment' class='control-label col-lg-2'>Key Skills:</label>"
print "<div class='col-lg-10'>"
print "<input  class='form-control' type=text id='keyskills' name='keyskills' required/>"
print "</div></div>"

print "<div class='form-group '>"
print "<label for='ccomment' class='control-label col-lg-2'>Qualification:</label>"
print "<div class='col-lg-10'>"
print "<input  class='form-control' type=text id='qualification' name='qualification' required/>"
print "</div></div>"

print "<div class='form-group '>"
print "<label for='ccomment' class='control-label col-lg-2'>Date of Joining:</label>"
print "<div class='col-lg-10'>"
print "<input  class='form-control' type=date id='doj' name='doj' required/>"
print "</div></div>"


print "<div class='form-group '>"
print "<label for='ccomment' class='control-label col-lg-2'>Employee Type:</label>"
print "<div class='col-lg-10'>"
print "<select class='form-control' id='employeetype' name='employeetype' required/>"
print "<option value='0'>---select---</option>"
print "<option value='PM'>Project Manager</option>"
print "<option value='PL'>Project Leader</option>"
print "<option value='PD'>Project Developer</option>"
print "</select>"
print "</div></div>"

print "<div class='form-group'>"
print "<div class='col-lg-offset-2 col-lg-10'>"
print "<button class='btn btn-primary' type='submit'>Save</button>"
print "<button class='btn btn-default' type='button'>Cancel</button>"
print "</div></div></form></div></div></section></div></div></section></section>"
# <!--main content end-->
print "<div class='text-right'>"
print "<div class='credits'>"
print "</div></div></section>"
# <!-- container section end -->

print "</body>"
print "</html>" 
