#!/Python27/python.exe
print "Content-type:text/html\r\n\r\n"
print "<html>"
print "<head>"
print "<meta charset='utf-8'>"
print "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
print "<link rel='shortcut icon' href='img/favicon.png'>"
print "<title>Employee Mastery</title>"
import JcLink
print "</head>"
print "<body class='login-img3-body'>"
print "<div class='container'>"
print "<form class='login-form' action='loginvalidate.py'>"        
print "<div class='login-wrap'>"
print "<p class='login-img'><i class='icon_lock_alt'></i></p>"
print "<div class='input-group'>"
print "<span class='input-group-addon'><i class='icon_profile'></i></span>"
print "<input type='text' class='form-control' name='username' placeholder='Username' autofocus required>"
print "</div>"
print "<div class='input-group'>"
print "<span class='input-group-addon'><i class='icon_key_alt'></i></span>"
print "<input type='password' class='form-control' name='password' placeholder='Password' required>"
print "</div>"
print "<div class='input-group'>"
print "<span class='input-group-addon'><i class='fa fa-user-plus'></i></span>"
print "<select class='form-control' name='usertype' required>"
print "<option value='0'>---Select User---</option>"
print "<option value='Admin'>Admin</option>"
print "<option value='PM'>Project Manager</option>"
print "<option value='PL'>Project Leader</option>"
print "<option value='PD'>Project Developer</option>"

print "</select>"
print "</div>"
print "<label class='checkbox'>"
print "<input type='checkbox' value='remember-me'> Remember me"
print "<span class='pull-right'> <a href='#'> Forgot Password?</a></span>"
print "</label>"
print "<button class='btn btn-primary btn-lg btn-block' type='submit'>Login</button>"
print "</div>"
print "</form></div> </body></html>"
