print "<link href='css/bootstrap.min.css' rel='stylesheet'>"
print "<link href='css/bootstrap-theme.css' rel='stylesheet'>"
print "<link href='css/elegant-icons-style.css' rel='stylesheet' />"
print "<link href='css/font-awesome.css' rel='stylesheet' />"
print "<link href='css/style.css' rel='stylesheet'>"
print "<link href='css/style-responsive.css' rel='stylesheet'>"
print "<link href='css/bootstrap.min.css' rel='stylesheet'>"
print "<link href='css/bootstrap-theme.css' rel='stylesheet'>"
print "<link href='css/elegant-icons-style.css' rel='stylesheet' />"
print "<link href='css/font-awesome.min.css' rel='stylesheet' />"
print "<link href='assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css' rel='stylesheet' />"
print "<link href='assets/fullcalendar/fullcalendar/fullcalendar.css' rel='stylesheet' />"
print "<link href='assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css' rel='stylesheet' type='text/css' media='screen'/>"
print "<link rel='stylesheet' href='css/owl.carousel.css' type='text/css'>"
print "<link href='css/jquery-jvectormap-1.2.2.css' rel='stylesheet'>"
print "<link rel='stylesheet' href='css/fullcalendar.css'>"
print "<link href='css/widgets.css' rel='stylesheet'>"
print "<link href='css/style.css' rel='stylesheet'>"
print "<link href='css/style-responsive.css' rel='stylesheet' />"
print "<link href='css/xcharts.min.css' rel=' stylesheet'>"
print "<link href='css/jquery-ui-1.10.4.min.css' rel='stylesheet'>"
print "<script src='js/jquery.js'></script>"
print "<script src='js/jquery-ui-1.10.4.min.js'></script>"
print "<script src='js/jquery-1.8.3.min.js'></script>"
print "<script type='text/javascript' src='js/jquery-ui-1.9.2.custom.min.js'></script>"
print "<script src='js/bootstrap.min.js'></script>"
print "<script src='js/jquery.scrollTo.min.js'></script>"
print "<script src='js/jquery.nicescroll.js' type='text/javascript'></script>"
print "<script src='assets/jquery-knob/js/jquery.knob.js'></script>"
print "<script src='js/jquery.sparkline.js' type='text/javascript'></script>"
print "<script src='assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js'></script>"
print "<script src='js/owl.carousel.js' ></script>"
print "<script src='js/fullcalendar.min.js'></script> <!-- Full Google Calendar - Calendar -->"
print "<script src='assets/fullcalendar/fullcalendar/fullcalendar.js'></script>"
print "<script src='js/calendar-custom.js'></script>"
print "<script src='js/jquery.rateit.min.js'></script>"
print "<script src='js/jquery.customSelect.min.js' ></script>"
print "<script src='assets/chart-master/Chart.js'></script>"
print "<script src='js/scripts.js'></script>"
print "<script src='js/sparkline-chart.js'></script>"
print "<script src='js/easy-pie-chart.js'></script>"
print "<script src='js/jquery-jvectormap-1.2.2.min.js'></script>"
print "<script src='js/jquery-jvectormap-world-mill-en.js'></script>"
print "<script src='js/xcharts.min.js'></script>"
print "<script src='js/jquery.autosize.min.js'></script>"
print "<script src='js/jquery.placeholder.min.js'></script>"
print "<script src='js/gdp-data.js'></script>"
print "<script src='js/morris.min.js'></script>"
print "<script src='js/sparklines.js'></script>"
print "<script src='js/charts.js'></script>"
print "<script src='js/jquery.slimscroll.min.js'></script>" 
